name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Install Node.js dependencies
      run: |
        cd frontend
        npm ci

    - name: Run ESLint
      run: |
        cd frontend
        npm run lint

    - name: Run Flake8
      run: |
        cd backend
        flake8 .

    - name: Run frontend unit tests
      run: |
        cd frontend
        npm test -- --coverage

    - name: Run backend unit tests
      run: |
        cd backend
        python -m pytest --cov=./ --cov-report=xml

    - name: Run integration tests
      run: |
        # HUMAN ASSISTANCE NEEDED
        # Add commands to run integration tests. This might involve setting up a test database,
        # starting both frontend and backend services, and running end-to-end tests.

    - name: Upload frontend test coverage
      uses: actions/upload-artifact@v2
      with:
        name: frontend-coverage
        path: frontend/coverage

    - name: Upload backend test coverage
      uses: actions/upload-artifact@v2
      with:
        name: backend-coverage
        path: backend/coverage.xml